spring.application.name=collab-editor-backend
server.port=${PORT:8080}

spring.data.mongodb.uri=mongodb+srv://collabuser:trNFCwr5X0KdnWgs@cluster0.lvbp8d3.mongodb.net/collabdb?retryWrites=true&w=majority&appName=Cluster0